## NumPy 
(NumPy stands for Numerical Python)


NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra and matrices.


**Why Use NumPy?**


In Python we have lists that serve the purpose of arrays, but they are slow to process.
**NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**
The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.


## Installation of NumPy

In [1]:
!pip install --upgrade pip
!pip install numpy

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 1.5 MB/s eta 0:00:01
   ----------------------- ---------------- 1.0/1.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------- ----------- 1.3/1.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 1.8 MB/s eta 0:00:00


ERROR: To modify pip, please run the following command:
C:\Users\Mostafa.Badr\AppData\Local\anaconda3\envs\depi_env\python.exe -m pip install --upgrade pip


In [2]:
#Create a NumPy ndarray Object

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
#Checking NumPy Version
print(np.__version__)

2.1.3


To create an ndarray, we can pass a list, tuple into the array() method, and it will be converted into an ndarray

In [4]:
# Try it yourself
# Done by students
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

**nested array:** are arrays that have arrays as their elements.


In [5]:
# 0-D Arrays
arr = np.array(42)
print(arr)

42


In [6]:
# 1-D Arrays
# Try it yourself
# Done by students
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
# 2-D Arrays
#An array that has 1-D arrays as its elements is called a 2-D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3-D arrays
# Try it yourself
# Done by students
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.


a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.




In [10]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Indexing


Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.



In [11]:
# Create a numpy array and access the first element in it
# Done by students
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [12]:
# Try accessing 2 elements in a numpy array and adding them together
# Done by students
print(arr[2] + arr[3])

7


In [13]:
# Access 2-D Arrays

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])
arr[0][1]

2nd element on 1st dim:  2


np.int64(2)

In [27]:
# Access 3-D Arrays
# Try it yourself
# Done by students
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[0][1][2])

6
6


## NumPy Array Slicing
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].



In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [16]:
# question for you?
# create a numpy array and slice the last 2 items in it.
# Done by students
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-2:])

[5 6]


In [17]:
#Step
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])

[2 5]


In [18]:
print(arr[::2])

[1 3 5 7]


In [19]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
# Try it yourself
# Done by students
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [20]:
# Checking the Data Type of an Array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


## Array Shape


The shape of an array is the number of elements in each dimension.


In [21]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
print(arr.shape)

(2, 4)


In [23]:
# Joining Array
# Joining means putting contents of two or more arrays in a single array.
arr1 = np.array([1, 2, 3, 6])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 6 4 5 6]


In [24]:
# Join two 2-D arrays along columns (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [25]:
# Join two 2-D arrays along rows (axis=0):
# Try it yourself
# Done by students
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
#Splitting Array
#Splitting is reverse operation of Joining.
arr = np.array([1, 2, 3, 4, 5, 6, 7])

newarr = np.array_split(arr, 2)

print(newarr)


[array([1, 2, 3, 4]), array([5, 6, 7])]
