## NumPy 
(NumPy stands for Numerical Python)


NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra and matrices.


**Why Use NumPy?**


In Python we have lists that serve the purpose of arrays, but they are slow to process.
**NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**
The array object in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.


## Installation of NumPy

In [ ]:
!pip install --upgrade pip
!pip install numpy

In [1]:
#Create a NumPy ndarray Object

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [2]:
#Checking NumPy Version
print(np.__version__)

1.26.4


To create an ndarray, we can pass a list, tuple into the array() method, and it will be converted into an ndarray

In [3]:
# Try it yourself
arr=np.array((1,2,3))
print(arr)


[1 2 3]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

**nested array:** are arrays that have arrays as their elements.


In [ ]:
# 0-D Arrays
arr = np.array(42)
print(arr)

In [5]:
# 1-D Arrays
# Try it yourself
arr=np.array([1,5,9])
print(arr)


[1 5 9]


In [6]:
# 2-D Arrays
#An array that has 1-D arrays as its elements is called a 2-D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
# 3-D arrays
# Try it yourself
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[1, 2, 3], [4, 5, 6]]])
print(arr)



[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [20]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.


a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.




In [21]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Indexing


Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.



In [24]:
# Create a numpy array and access the first element in it
arr=np.array([2,6,9])
print(arr[0])


2


In [25]:
# Try accessing 2 elements in a numpy array and adding them together
arr=np.array([2,6,9])
print(sum(arr[0:2]))


8


In [26]:
# Access 2-D Arrays

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])
arr[0][1]

2nd element on 1st dim:  2


2

In [27]:
# Access 3-D Arrays
# Try it yourself

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,0])


10


## NumPy Array Slicing
We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].



In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [29]:
# question for you?
# create a numpy array and slice the last 2 items in it.
print(arr[-2:])


[6 7]


In [30]:
#Step
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])


[2 5]


In [31]:
print(arr[::2])

[1 3 5 7]


In [33]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
# Try it yourself

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0,1:4])
print(arr[1,1:4])

[2 3 4]
[7 8 9]


In [34]:
# Checking the Data Type of an Array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


## Array Shape


The shape of an array is the number of elements in each dimension.


In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
print(arr.shape)

(2, 4)


In [37]:
# Joining Array
# Joining means putting contents of two or more arrays in a single array.
arr1 = np.array([1, 2, 3, 6])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 6 4 5 6]


In [43]:
# Join two 2-D arrays along columns (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)


print(arr)
print(arr.ndim)

[[1 2 5 6]
 [3 4 7 8]]
2


In [41]:
# Join two 2-D arrays along rows (axis=0):
# Try it yourself
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
#Splitting Array
#Splitting is reverse operation of Joining.
arr = np.array([1, 2, 3, 4, 5, 6, 7])

newarr = np.array_split(arr, 2)

print(newarr)

[array([1, 2, 3, 4]), array([5, 6, 7])]
